### ISSUE TITLE
Log Bug tracker- Backend

### ISSUE THREAD

**Issue by HakanSahin11** [HakanSahin11/SKP-INTRA#16]
This section is for whenever a bug appears it will then be logged locally with error messages, conditions and where it took place.

- Research Nlog and its implementations
- Try setting the log up using Nlog

**Comment by Prazdnik** [comment]
Hi, You can connect a free library [NLog](https://nlog-project.org/). I use it every day at work to catch bugs.

**Comment by HakanSahin11** [comment]
Hi, thanks for the advice, we will make sure to look into NLog and its functionalities.
